import {marked} from 'marked';import sanitizeHtml from 'sanitize-html';
const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const md=value=>sanitizeHtml(marked.parse(String(value||'')),{allowedTags:['p','br','strong','em','ul','ol','li','h1','h2','h3','h4','blockquote','code','pre','table','thead','tbody','tr','th','td','hr','sup','sub'],allowedAttributes:{},allowedSchemes:[]});
const choices=a=>a.activity_type==='MULTIPLE_CHOICE'?`<fieldset class="choices" data-answer="${escape(a.correct_choice_id)}"><legend>Choose one answer</legend>${a.choices.map(c=>`<label><input type="radio" name="answer" value="${escape(c.choice_id)}"> <b>${escape(c.choice_id)}.</b> ${escape(c.text)}</label>`).join('')}<button type="button" id="check">Check answer</button><p id="result" aria-live="polite"></p></fieldset>`:'';
export function renderActivity({activity,assetNames,typeLabel}){
 const blocks=activity.blocks.map((b,i)=>`<section class="block kind-${escape(b.kind.toLowerCase())}"><span class="kind">${escape(b.kind)}</span>${md(b.markdown)}</section>`).join('');
 const template=process.env.HTML_TEMPLATE||'classroom';
 const themes={classroom:['#14213d','#fca311','#f4f7fb'],colorful:['#5b21b6','#f97316','#fff7ed'],worksheet:['#111827','#2563eb','#ffffff'],geometry:['#064e3b','#10b981','#ecfdf5'],minimal:['#374151','#6b7280','#f9fafb']};
 const [primary,accent,background]=themes[template]||themes.classroom;
 const imageBlocks=(activity.image_requests||[]).map(x=>{const fileName=assetNames?.[x.image_id];return `<figure class="generated-image">${fileName?`<img src="assets/${escape(fileName)}" alt="${escape(x.purpose)}">`:`<div class="image-placeholder" data-image-id="${escape(x.image_id)}">Image unavailable</div>`}<figcaption>${escape(x.purpose)}</figcaption></figure>`;}).join('');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src 'self' data:; style-src 'unsafe-inline'; script-src 'unsafe-inline'; object-src 'none'; base-uri 'none'; form-action 'none'"><title>${escape(activity.title)}</title><style>:root{font-family:Inter,system-ui,sans-serif;color:#14213d;background:${background}}*{box-sizing:border-box}body{margin:0}header{background:${primary};color:#fff;padding:24px}header p{color:${accent};font-weight:700}main{max-width:900px;margin:auto;padding:24px}.objective,.block,.choices,details,.generated-image{background:#fff;border:1px solid #dce4ee;border-radius:12px;padding:20px;margin:16px 0}.kind{font-size:11px;font-weight:800;color:${primary}}.choices label{display:block;padding:9px}.choices button{padding:9px 14px}img{max-width:100%;max-height:560px;display:block;margin:auto}.image-placeholder{min-height:130px;display:grid;place-items:center;border:2px dashed ${accent};color:${primary};text-align:center;padding:16px}figcaption{text-align:center;margin-top:8px;font-size:.9rem}details summary{cursor:pointer;font-weight:700}button:focus,input:focus{outline:3px solid ${accent}} @media(max-width:600px){main{padding:12px}}</style></head><body><header><p>${escape(typeLabel)} · ${escape(template)} template</p><h1>${escape(activity.title)}</h1></header><main><section class="objective"><b>Learning objective</b><p>${escape(activity.objective)}</p></section><section>${md(activity.instructions_markdown)}</section>${imageBlocks}${blocks}${choices(activity)}<details><summary>Show solution and explanation</summary>${md(activity.solution_markdown)}</details></main><script>(()=>{const b=document.querySelector('#check');if(b)b.addEventListener('click',()=>{const f=b.closest('fieldset'),v=f.querySelector('input:checked')?.value,r=document.querySelector('#result');r.textContent=!v?'Select an answer first.':v===f.dataset.answer?'Correct ✓':'Not yet. Review the explanation and try again.';});})();</script></body></html>`;
}
export function renderPackageIndex({title,activities}){const cards=activities.map((a,i)=>`<li><a href="activities/${escape(a.activity_id)}/index.html">${i+1}. ${escape(a.title)}</a><span>${escape(a.activity_type)} · Process ${escape(a.process_sequence)}</span></li>`).join('');return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><style>body{font-family:Inter,system-ui;max-width:900px;margin:auto;padding:30px;color:#14213d}li{display:grid;gap:5px;padding:16px;margin:10px 0;border:1px solid #ddd;border-radius:10px}a{font-weight:700}span{color:#687487}</style></head><body><h1>${escape(title)}</h1><p>Approved activities</p><ol>${cards}</ol></body></html>`;}
