import {useEffect,useMemo,useState} from 'react';
import Markdown from 'react-markdown';
import gfm from 'remark-gfm';
import LayoutCanvas from './LayoutCanvas.jsx';
import './source-preview.css';

async function api(url,init={}){const response=await fetch(url,init),text=await response.text();let data;try{data=text?JSON.parse(text):{};}catch{data={error:text}}if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data;}
const send=(url,body,method='POST')=>api(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
const Text=({children})=><Markdown remarkPlugins={[gfm]}>{children||''}</Markdown>;

export default function App(){
 const [options,setOptions]=useState([]),[types,setTypes]=useState([]),[book,setBook]=useState(''),[chapter,setChapter]=useState('');
 const [plans,setPlans]=useState([]),[planId,setPlanId]=useState(''),[bundle,setBundle]=useState(null),[activeProcessId,setActiveProcessId]=useState('');
 const [selected,setSelected]=useState({}),[variants,setVariants]=useState({}),[instruction,setInstruction]=useState('');
 const [activities,setActivities]=useState([]),[activityId,setActivityId]=useState(''),[activity,setActivity]=useState(null),[packages,setPackages]=useState([]);
 const [busyProcessId,setBusyProcessId]=useState(''),[error,setError]=useState(''),[comment,setComment]=useState(''),[reload,setReload]=useState(0),[previewOpen,setPreviewOpen]=useState(false),[sourceOpen,setSourceOpen]=useState(false),[sourcePreview,setSourcePreview]=useState(null),[sourceLoading,setSourceLoading]=useState(false),[showSourceBoxes,setShowSourceBoxes]=useState(false);

 useEffect(()=>{let active=true;Promise.all([api('/api/options'),api('/api/activity-types')]).then(([rows,catalog])=>{if(!active)return;setOptions(rows);setTypes(catalog);const firstBook=rows[0]?.book_id||'';setBook(firstBook);setChapter(rows.find(row=>row.book_id===firstBook)?.chapter_id||'');}).catch(value=>active&&setError(value.message));return()=>{active=false;};},[reload]);
 useEffect(()=>{let active=true;setPlans([]);setPlanId('');setBundle(null);setActiveProcessId('');if(!book||!chapter)return()=>{active=false;};api('/api/plans?'+new URLSearchParams({book_id:book,chapter_id:chapter})).then(result=>{if(!active)return;setPlans(result.items);setPlanId(result.items[0]?.plan_id||'');}).catch(value=>active&&setError(value.message));return()=>{active=false;};},[book,chapter,reload]);
 useEffect(()=>{let active=true;setBundle(null);setActivities([]);setPackages([]);setActivityId('');setActivity(null);setPreviewOpen(false);setSelected({});setVariants({});if(!planId)return()=>{active=false;};Promise.all([api(`/api/plans/${encodeURIComponent(planId)}`),api(`/api/plans/${encodeURIComponent(planId)}/activities`),api(`/api/plans/${encodeURIComponent(planId)}/packages`)]).then(([nextBundle,nextActivities,nextPackages])=>{if(!active)return;setBundle(nextBundle);setActivities(nextActivities);setPackages(nextPackages);const firstProcessId=nextBundle.processes[0]?.process_id||'';setActiveProcessId(firstProcessId);setActivityId(nextActivities.find(item=>item.process_id===firstProcessId)?.activity_id||'');}).catch(value=>active&&setError(value.message));return()=>{active=false;};},[planId]);
 useEffect(()=>{let active=true,timer;setActivity(null);if(!activityId)return()=>{active=false;};async function poll(){try{const value=await api(`/api/activities/${encodeURIComponent(activityId)}`);if(!active)return;setActivity(value);if(['QUEUED','RUNNING'].includes(value.generation_status)){timer=setTimeout(async()=>{const rows=await api(`/api/plans/${encodeURIComponent(planId)}/activities`);if(active)setActivities(rows);poll();},4000);}}catch(value){if(active)setError(value.message);}}poll();return()=>{active=false;clearTimeout(timer);};},[activityId,planId]);
 useEffect(()=>{if(!previewOpen)return;const close=event=>{if(event.key==='Escape')setPreviewOpen(false);};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close);},[previewOpen]);
 useEffect(()=>{let active=true;if(!sourceOpen||!planId)return()=>{active=false;};setSourceLoading(true);setSourcePreview(null);api(`/api/plans/${encodeURIComponent(planId)}/source-preview`).then(value=>active&&setSourcePreview(value)).catch(value=>active&&setError(value.message)).finally(()=>active&&setSourceLoading(false));return()=>{active=false;};},[sourceOpen,planId]);

 const books=[...new Set(options.map(row=>row.book_id))].filter(Boolean);
 const chapters=[...new Set(options.filter(row=>row.book_id===book).map(row=>row.chapter_id))].filter(Boolean);
 const activeProcess=bundle?.processes.find(item=>item.process_id===activeProcessId);
 const processActivities=useMemo(()=>activities.filter(item=>item.process_id===activeProcessId),[activities,activeProcessId]);
 const selectionKey=(processId,type)=>`${processId}:${type}`;
 function changeBook(value){setBook(value);setChapter(options.find(row=>row.book_id===value)?.chapter_id||'');}
 function selectProcess(processId){setActiveProcessId(processId);setActivityId(activities.find(item=>item.process_id===processId)?.activity_id||'');setComment('');setError('');}
 function openActivity(activityId){setActivityId(activityId);setComment('');setError('');setPreviewOpen(true);}
 function openSourcePreview(){setSourceOpen(true);setError('');}
 function toggleType(processId,type){const key=selectionKey(processId,type);setSelected(current=>({...current,[key]:!current[key]}));}

 async function createForProcess(processId){
  const selections=types.filter(type=>selected[selectionKey(processId,type.type)]).map(type=>({process_id:processId,activity_type:type.type,variants:Number(variants[selectionKey(processId,type.type)]||1)}));
  if(!selections.length){setError('Select at least one activity type for this process.');return;}
  setBusyProcessId(processId);setError('');
  try{const result=await send(`/api/plans/${encodeURIComponent(planId)}/activities`,{selections,additional_instruction:instruction});const rows=await api(`/api/plans/${encodeURIComponent(planId)}/activities`);setActivities(rows);setActivityId(result.activity_ids[0]||'');setPreviewOpen(true);}
  catch(value){setError(value.message);}finally{setBusyProcessId('');}
 }
 async function review(decision){setBusyProcessId(activeProcessId);setError('');try{await send(`/api/activities/${encodeURIComponent(activityId)}/review`,{decision,comment},'PUT');const [updated,rows]=await Promise.all([api(`/api/activities/${encodeURIComponent(activityId)}`),api(`/api/plans/${encodeURIComponent(planId)}/activities`)]);setActivity(updated);setActivities(rows);}catch(value){setError(value.message);}finally{setBusyProcessId('');}}
 async function publish(){setBusyProcessId('PUBLISH');setError('');try{const result=await send(`/api/plans/${encodeURIComponent(planId)}/packages`,{});setPackages(await api(`/api/plans/${encodeURIComponent(planId)}/packages`));window.alert(`Formal package created: ${result.index_html_blob_path}`);}catch(value){setError(value.message);}finally{setBusyProcessId('');}}

 return <div className="app-shell">
  <header><div><span className="eyebrow">Approved plan → process activities → package</span><h1>Lesson Activity Publishing Studio</h1></div><button onClick={()=>setReload(value=>value+1)}>Refresh</button></header>
  <section className="filters"><label>Book<select value={book} onChange={event=>changeBook(event.target.value)}>{books.map(value=><option key={value}>{value}</option>)}</select></label><label>Chapter<select value={chapter} onChange={event=>setChapter(event.target.value)}>{chapters.map(value=><option key={value}>{value}</option>)}</select></label><label>Learning plan<select value={planId} onChange={event=>setPlanId(event.target.value)}>{plans.map(plan=><option value={plan.plan_id} key={plan.plan_id}>{plan.source_title||plan.fine_page_id}</option>)}</select></label><label>Formal packages<input readOnly value={packages.length}/></label></section>
  {error&&<div role="alert" className="error">{error}</div>}
  {!bundle?<p className="empty">Select an approved learning plan.</p>:<>
   <section className="plan-summary"><div><span className="eyebrow">Approved learning plan</span><h2>{bundle.source.title}</h2></div><div className="metadata"><span><b>Grade</b>{bundle.plan.grade}</span><span><b>Processes</b>{bundle.processes.length}</span><span><b>Activities</b>{activities.length}</span></div></section>
   <nav className="process-tabs" role="tablist" aria-label="Learning processes">{bundle.processes.map(learningProcess=>{const count=activities.filter(item=>item.process_id===learningProcess.process_id).length;return <button type="button" role="tab" aria-selected={activeProcessId===learningProcess.process_id} className={activeProcessId===learningProcess.process_id?'chosen':''} key={learningProcess.process_id} onClick={()=>selectProcess(learningProcess.process_id)}><span>Process {learningProcess.sequence_number}</span><strong>{learningProcess.title}</strong><small>{count} {count===1?'activity':'activities'}</small></button>;})}<button type="button" className="source-preview-button" onClick={openSourcePreview}>Original Markdown + layout</button></nav>
   <main><aside><div className="list-title"><span>Process activities</span><span>{processActivities.length}</span></div>{!processActivities.length&&<p className="muted">No activity has been generated for this process.</p>}{processActivities.map(item=><button key={item.activity_id} className={'page-row '+(activityId===item.activity_id?'active':'')} onClick={()=>openActivity(item.activity_id)}><span className={'status '+String(item.review_status).toLowerCase()}>{item.review_status}</span><strong>{item.title||types.find(type=>type.type===item.activity_type)?.label||item.activity_type}</strong><small>{types.find(type=>type.type===item.activity_type)?.label||item.activity_type} · Variant {item.variant_number}</small><small>{item.generation_status} · Click to preview</small></button>)}</aside>
    <article>{activeProcess&&<section className="process-workspace" role="tabpanel"><div className="article-head"><div><span className="eyebrow">Process {activeProcess.sequence_number}</span><h2>{activeProcess.title}</h2></div></div><Text>{activeProcess.instruction_markdown}</Text><p><b>Success criteria:</b> {activeProcess.success_criteria}</p>{activeProcess.prerequisites.length>0&&<details><summary>Prerequisites ({activeProcess.prerequisites.length})</summary>{activeProcess.prerequisites.map(item=><div key={item.prerequisite_id}><b>{item.title}</b><Text>{item.remediation_markdown}</Text></div>)}</details>}
     <section className="review-panel"><h3>Choose activities for this process</h3><p className="muted">Only this process will be queued when you click the button below.</p><div className="activity-grid">{types.map(type=>{const key=selectionKey(activeProcess.process_id,type.type);return <div className={'activity-option '+(selected[key]?'picked':'')} key={type.type}><label className="check"><input type="checkbox" checked={!!selected[key]} onChange={()=>toggleType(activeProcess.process_id,type.type)}/><span>{type.label}<small>{type.type}</small></span></label>{selected[key]&&<select value={variants[key]||1} onChange={event=>setVariants(current=>({...current,[key]:Number(event.target.value)}))}><option value="1">1 variant</option><option value="2">2 variants</option><option value="3">3 variants</option></select>}</div>;})}</div><label>Specific instruction for the selected activities<textarea maxLength="1000" value={instruction} onChange={event=>setInstruction(event.target.value)} placeholder="Optional process-specific preference"/></label><button className="approve create-process" disabled={!!busyProcessId} onClick={()=>createForProcess(activeProcess.process_id)}>{busyProcessId===activeProcess.process_id?'Creating…':'Create Queued Activity'}</button></section>
     <section className="review-panel preview-launch"><h3>Preview and review</h3><p>Select an activity from the left. Its generated page and review controls will open in a separate window.</p>{activityId&&<button className="secondary" onClick={()=>setPreviewOpen(true)}>Open selected activity</button>}</section>
     <section className="review-panel"><h3>Publish formal package</h3><p>Only approved activities are included. Every process must have at least one approved activity.</p><button className="approve" disabled={!!busyProcessId} onClick={publish}>{busyProcessId==='PUBLISH'?'Publishing…':'Publish approved activities'}</button>{packages.map(item=><p key={item.package_id}>v{item.version_number} · {item.review_status} · <a href={`/api/packages/${item.package_id}/files/index.html`} target="_blank" rel="noreferrer">Preview</a></p>)}</section>
    </section>}</article>
   </main>
  </>}
  {previewOpen&&<div className="modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setPreviewOpen(false);}}><section className="preview-modal" role="dialog" aria-modal="true" aria-labelledby="preview-title"><div className="modal-header"><div><span className="eyebrow">Preview and review</span><h2 id="preview-title">{activity?.title||'Generated activity'}</h2></div><button className="modal-close" type="button" aria-label="Close preview" onClick={()=>setPreviewOpen(false)}>×</button></div><div className="modal-status">{!activity?<span>Loading activity…</span>:<><span><b>Generation:</b> {activity.generation_status}</span><span><b>Review:</b> {activity.review_status}</span></>}</div>{activity?.generation_error&&<div className="error modal-error">{activity.generation_error}</div>}{activity?.generation_status==='SUCCEEDED'&&<div className="modal-body"><iframe className="preview modal-preview" title="Activity preview" src={`/api/activities/${encodeURIComponent(activityId)}/files/index.html`}/><aside className="modal-review"><h3>Review decision</h3><label>Review comment<textarea value={comment} maxLength="4000" onChange={event=>setComment(event.target.value)} placeholder="Optional reviewer comment"/></label><div className="review-actions vertical"><button className="approve" disabled={!!busyProcessId} onClick={()=>review('APPROVED')}>Approve</button><button className="changes" disabled={!!busyProcessId} onClick={()=>review('NEEDS_CHANGES')}>Needs changes</button><button className="reject" disabled={!!busyProcessId} onClick={()=>review('REJECTED')}>Reject</button></div></aside></div>}<div className="modal-footer"><button className="secondary" onClick={()=>setPreviewOpen(false)}>Close</button></div></section></div>}
  {sourceOpen&&<div className="modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setSourceOpen(false);}}><section className="source-modal" role="dialog" aria-modal="true" aria-labelledby="source-preview-title"><div className="modal-header"><div><span className="eyebrow">Approved source page</span><h2 id="source-preview-title">{sourcePreview?.title||bundle.source.title}</h2></div><button className="modal-close" type="button" aria-label="Close source preview" onClick={()=>setSourceOpen(false)}>×</button></div>{sourceLoading&&<p className="empty">Loading original Markdown and Azure layout…</p>}{sourcePreview&&!sourceLoading&&<><div className="source-toolbar"><button className={!showSourceBoxes?'secondary active':''} onClick={()=>setShowSourceBoxes(false)}>Markdown</button><button className={showSourceBoxes?'secondary active':''} onClick={()=>setShowSourceBoxes(true)}>Layout reconstruction</button><label><input type="checkbox" checked={showSourceBoxes} onChange={event=>setShowSourceBoxes(event.target.checked)}/> Show layout boxes</label></div>{showSourceBoxes?<div className="source-layout"><LayoutCanvas data={sourcePreview.layout} figureUrls={sourcePreview.figureUrls} showBoxes={showSourceBoxes}/></div>:<div className="source-markdown"><Markdown remarkPlugins={[gfm]} components={{img:({src,alt})=>{const match=String(src||'').match(/figure-(\d+)\.(?:png|jpe?g|webp)$/i);const url=match?sourcePreview.figureUrls[Number(match[1])-1]:src;return <img src={url||''} alt={alt||''}/>;}}}>{sourcePreview.markdown||''}</Markdown></div>}</>}<div className="modal-footer"><button className="secondary" onClick={()=>setSourceOpen(false)}>Close</button></div></section></div>}
 </div>;
}
